Breaking change - remove property is_fitted_, introduce method is_fitted(), metadata_ => get_metadata()
AssertionError: By convention, attributes ending with '_' are estimated from data in scikit-learn. Consequently they should not be initialized in the constructor of an estimator but in the fit method.

ref:3070cda4fa697757430ede3c406a2c695012b5e7