[yatest] NBS-3062: write backtrace to html with text mode
```
Traceback (most recent call last):
File "library/python/testing/yatest_common/yatest/common/process.py", line 395, in verify_no_coredumps
self._recover_core()
File "library/python/testing/yatest_common/yatest/common/process.py", line 292, in _recover_core
backtrace_to_html(bt_filename, pbt_filename)
File "library/python/testing/yatest_common/yatest/common/process.py", line 737, in backtrace_to_html
coredump_filter.filter_stackdump(bt_filename, stream=afile)
File "sandbox/sdk2/helpers/coredump_filter/__init__.py", line 1294, in filter_stackdump
return dumper.dump()
File "sandbox/sdk2/helpers/coredump_filter/__init__.py", line 1130, in dump
html_prolog(self.stream, self.timestamp)
File "sandbox/sdk2/helpers/coredump_filter/__init__.py", line 927, in html_prolog
stream.write(prolog.format(
TypeError: a bytes-like object is required, not 'str'
```

ref:7fcde262e0721fe8fb8e23fe58b3789346eaeb6d