Suppress some extra errors in the flake8's config found during migration
issue:DEVTOOLS-6556

E122 - sandbox/taskbox/model/update.py:182: [E122] continuation line missing indentation or outdented
E225 - robot/jupiter/tools/quality_acceptance/metrics.py:152: [E225] missing whitespace around operator
E306 - dict/ontodb/metrics/ontofields_sbs/st_05_stats.py:127: [E306] expected 1 blank line before a nested definition, found 0
F401 - ads/libs/py_ml_factors/matrixnet/learn_preprocessors.py:42: [F401] 'landing_factors.JoinLandingFactors' imported but unused
F403 - ads/watchman/contrib/flask-restplus-patched/flask_restplus_patched/__init__.py:1: [F403] 'from flask_restplus import *' used
F405 - typing\narcadia/yweb/tellurium/ui/dto.py:260: [F405] 'Dict' may be undefined, or defined from star imports: typing
F632 - yabs/awaps_pvl/pvl/__main__.py:32: [F632] use ==/!= to compare constant literals (str, bytes, int, float, tuple)
F633 - quality/logs/baobab/api/python/baobab/common/error_handler.py:40: [F633] use of >> is invalid with print function
F811 - modadvert/programs/dyn_disclaimers/ut/test_get_disclaimers.py:1084: [F811] redefinition of unused 'handler' from line 5
F821 - infra/watchdog/src/app/watchdog.py:243: [F821] undefined name 'six'
F841 - metrika/admin/python/scripts/jrun/__main__.py:52: [F841] local variable 'err' is assigned to but never used

ref:3fda27533e6307de2be6faac95a8d5986719c892