Mute -Wdeprecated-declarations error when thread sanitizer enabled on darwin platform
При сборке проектов с ```--sanitize=thread``` под **darwin**, по умолчанию попадет ```util``` и его часть ```system/context.h```, где в случае ```thread_sanitizer_enabled``` выставляется ```USE_UCONTEXT_CONT```, что приводит к использованию [депрекейтнутного](https://opensource.apple.com/source/libplatform/libplatform-125/include/ucontext.h.auto.html) ```<ucontext.h>``` из [macos_sdk](https://a.yandex-team.ru/arcadia/build/platform/macos_sdk/ya.make?rev=rXXXXXX#L6).


Без должных изменений, сборка падает с ошибкой.
```In file included from /Users/hiddenpath/.ya/build/build_root/fnjm/000128/util/all_system_1.cpp:13:
In file included from /Users/hiddenpath/arcadia/util/system/context.cpp:31:
In file included from /Users/hiddenpath/arcadia/util/system/context.h:46:
/Users/hiddenpath/.ya/tools/v4/2088833948/usr/include/ucontext.h:51:2: error: The deprecated ucontext routines require _XOPEN_SOURCE to be defined
#error The deprecated ucontext routines require _XOPEN_SOURCE to be defined
 ^
In file included from /Users/hiddenpath/.ya/build/build_root/fnjm/000128/util/all_system_1.cpp:13:
In file included from /Users/hiddenpath/arcadia/util/system/context.cpp:31:
/Users/hiddenpath/arcadia/util/system/context.h:68:9: error: use of undeclared identifier 'getcontext'
        getcontext(&Ctx_);
        ^
/Users/hiddenpath/arcadia/util/system/context.h:72:9: error: use of undeclared identifier 'getcontext'
        getcontext(&Ctx_);
        ^
/Users/hiddenpath/arcadia/util/system/context.h:80:9: error: use of undeclared identifier 'makecontext'
        makecontext(&Ctx_, (ucontext_func_t)ContextTrampoLine, 1, c.TrampoLine);
        ^
/Users/hiddenpath/arcadia/util/system/context.h:87:9: error: use of undeclared identifier 'swapcontext'
        swapcontext(&Ctx_, &next->Ctx_);
        ^
5 errors generated.
Failed