Allow to run py.test with arcadia packages
PyCrypto package is used for tests here: https://github.yandex-team.ru/InfraComponents/mds-proxy-qa/blob/cb5baa11b059a1ba7bedac238d3db05a0b35b79f/tests/api/aes_256_cbc_decrypt.py#L3.
Without this mds proxy tests failed with:
"
from Crypto.Cipher import _AES
E   ImportError: cannot import name _AES
"

The reason is that _AES is a ".so" file, and pymds cannot imported this.
Probably there is a way to allow arcadia python interpretator to work with already installed ".so" files, but documentation doesn't help about this.

Also when PyCrypto was marked as deprecated here https://st.yandex-team.ru/SUBBOTNIK-2976,
author doesn't recommend a single replacement (neither I spent enough time to find one),
so one more exception for tests shouldn't be a problem.

ref:99f2b2ce5900807d8801028469ceb235159e49ba