[catboost]: Get rid of implicitly declared default copy constructor in order to avoid -Wdeprecated-copy error
https://timsong-cpp.github.io/cppwp/n4659/depr.impldec

```
The implicit definition of a copy constructor as defaulted is deprecated if the class has
a user-declared copy assignment operator or a user-declared destructor. The implicit definition
of a copy assignment operator as defaulted is deprecated if the class has a
user-declared copy constructor or a user-declared destructor (15.4, 15.8).
In a future revision of this International Standard, these implicit definitions could become deleted (11.4).
```

It blocks update of standard library: https://a.yandex-team.ru/review/5084628/details

```
$(SOURCE_ROOT)/catboost/cuda/cuda_lib/cuda_base.h:291:9: error: definition of implicit copy assignment operator for 'TCudaDeviceProperties' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
        TCudaDeviceProperties(const TCudaDeviceProperties& other) = default;
        ^
```