Fix build with gcc
It fails because gcc infers that the auto argument is a pointer rather than a reference:

error: request for member 'Type' in 'ctrDescription', which is of pointer type 'NCatboostOptions::TCtrDescription* const' (maybe you meant to use '->' ?)

Note: mandatory check (NEED_CHECK) was skipped
ref:214a592c2ae0772e0bcd1c1eb1e09aaedf0a0777