Fix definition of TTimeInfo to workaround an MSVC issue
MSVC 2015 complaints thus:
cuda\methods\boosting_progress_tracker.cpp(79): error C2664: 'void std::__y1::vector>::push_back(TTimeInfo &&)': cannot convert argument 1 from 'initializer list' to 'const TTimeInfo &'

ref:4bd747430f63df4faed2643a2711f01edcf93392